Update sdk.ts
imRohan/Pantry pull request #203
Opened 2024-03-16 17:39 UTC by Atoo35

I am back with adding a new rust client for the pantry API.

2024-03-18 14:04 UTC, imRohan commented
Cool, I'm excited that there is a Rust SDK available for Pantry!

Looks like the linter is not happy with your changes, you might be missing a comma somewhere.

Also, let's rename your PR to `Add Rust Client to List of SDK's`

2024-03-18 14:04 UTC, imRohan requested changes
Cool, I'm excited that there is a Rust SDK available for Pantry!

Looks like the linter is not happy with your changes, you might be missing a comma somewhere.

Also, let's rename your PR to Add Rust Client to List of SDK's

2024-03-18 21:09 UTC, Atoo35 commented
@imRohan  I am excited too, learning rust along with building.
Anyway I fixed both the changes requested!!

2024-03-19 13:27 UTC, imRohan approved these changes

2024-03-19 13:28 UTC, merged

2025-10-30 18:06 UTC, imRohan commented
Your changes are now live on prod 🎉

2025-10-30 18:48 UTC, Atoo35 commented
It's been 2 years lol. Completely forgot about this

2025-10-30 18:58 UTC, imRohan commented
@Atoo35 Lol, better late then never!