Changed to double quotes in npm script
imRohan/Pantry pull request #86
Opened 2021-09-05 14:11 UTC by kaffarell

Single quotes don't work on windows, so I changed to double quotes and
escaped them with a backslash (should work on all platforms, tried on
windows and linux).

2021-09-07 01:22 UTC, imRohan commented
I merged in the latest changes from master which lets the CI action run on pull requests. Could you please squash all of the commits into one please? Thanks!

2021-09-07 06:13 UTC, kaffarell commented
👍 Fixed it

2021-09-07 13:09 UTC, imRohan requested changes
The intended changes to `package.json` look good! 👍  I see there are other changes that you'll need to address, maybe rebase on master since these changes currently exist.

Also, could you please update your commit message to match the PR description? I've added a pull request template [here](https://github.com/imRohan/Pantry/blob/master/.github/pull_request_template.md)

2021-09-08 14:35 UTC, kaffarell commented
Sorry for the mess, I accidentaly updated the kaffarell/master branch with unrelated changes from the imRohan/master branch. Reverted these changes and made a new commit with only the intended changes (also following the guidelines). Hope this works!

2021-09-08 18:12 UTC, merged